export enum DRIVE_MAPPING {
    HERO = "1s-SF-K93AQgzc2azVfu0Pjk337rKvqFh",
    ABOUT = "1uGTk5rCsOWlwC0pJnAWNo3O1TmR9mqt6",
    SERVICE = "1UIv4fY0pxCttKVJLA15UEGeYVAGknYMt",
    SERVICE_WEDDING = "1UIv4fY0pxCttKVJLA15UEGeYVAGknYMt",
    SERVICE_POTRAIT = "1EYNwsejGzXzNsrnmggHoZOvAkbBn98vS",
    SERVICE_KINDER = "11jW9dVmBZqeLuoO4NUobiGsufz7mn8z9",
    SERVICE_ENGAGEMENT = "1v1P_EmQ9StRlFy3rELwat-IZBbpf-nFs",
    PROJECT_WEDDING = "1MeI4Te2jEdObyb0AEmFnb2_-yMo9rggo",
    PROJECT_WEDDING_1 = "1pnOO8HyezHdoOKo1xa2ihZqXvC1irt6l",
    PROJECT_SAVE_THE_DATE = "1i6pfm6KklgWj775wh2N29vHjc2iJqrIm",
    PROJECT_POTRAIT = "1SEBvyXzg0G1Ccw4BaKOvtBJ90REYjljJ",
    PROJECT_MATERNITY = "11dlianXkYDBSKzfBMeVowJUogxRHDLsu",
    PROJECT_KINDER = "1EXNaiaAtGdYkubki_p5x35ABu2fAHlNW",
    PROJECT_FESTIVALS = "1MFxlvh3rxDgZ-704hRHa72MFf-nerRnX",
    PROJECT_ENGAGEMENT = "1GdVpNUCsd_na_AAvoS2Pcd7fUKdVRtx7",
    CONTACT = "1mQVksqvKBSam3AM50AdD8bsJFlrfkhKw"
}

export const DRIVE_API_KEY = 'AIzaSyAn13cgWr4uTW-2UEhF5Pt3a96WjTVQeqA'